hw09/single_pages/urls.py
from django.urls import path
from . import views
app_name = "single_pages"
urlpatterns = [
    path('About me/', views.about_me, name='about_me'),
    path('NaverBlog/', views.naverblog, name='naverblog'),
    path('Blog/', views.blog, name='blog'),
    path('Armylife/', views.army_life, name='army_life'),
    path('', views.landing, name='landing'),
]

hw09/single_pages/templates/single_pages/about_me.html
{% extends './layout.html' %}
{% load static%}
{% block content %}



  <h1>자기 소개</h1>
        <h3>안녕하십니까. 제 이름은 이현규입니다.</h3>
        <h3>2002년생(23살)이고 현재 전북대학교 스마트팜학과에 재학중입니다.</h3>

        <img src="{% static 'single_pages/images/profile.jpg' }" width="200px">
        <hr/>

        <h3>(취미)</h3>
        <h4>: 저녁에 (혼자) 제가 좋아하는 노래를 들으며 러닝하는 것을 좋아합니다.
            또는 친구들과 함께 축구 or 풋살도 좋습니다. </h4></p>
        <h3>(MBTI)</h3> </p>

        <h4>: ENFP 입니다. E와 I의 비율의 거의 비슷하지만 "E"가  55%이니 ENFP로 하지요. ^_^ </h4></p>
        <h3>(좋아하는 음식)</h3> </p>

        <h4>: 저는 특히 서구권 음식을 좋아하는 것 같습니다. (스파게티, 피자, 햄버거를 특히 !@ 좋아합니다.)
        </p>BUT 언제나 맛있는 한식도 환영입니다.(누구나 아는 김치찌개, 갈비찜, 제육볶음, etc..)</h4>
        <hr/>
        <h3>(거주지) </h3></p>
        <h4>: 제 본가는 서울 금천구에 위치하고 있습니다. </h4></p>

        <h3>(가족 관계)</h3> </p>
        <h4>: 아버지, 어머니 그리고 제 위에 형 2명이 있습니다. (총 5명)</h4> </p>
        <h3>(스마트팜학과에 진학한 이유)</h3> </p> <h4> : 고등학교 시절, 스마트팜이라는 농업 분야를 처음 접했고 흥미가 생기기
    
        시작했습니다. </p>
        대부분이 생각하는 농업은 힘들고, 지구 대기 날씨의 영향이 절대적이고 그 해 농사의 결과를 결정하는 것이었습니다. </p>
        하지만 스마트팜 기술의 발전을 통해 이러한 문제점들과 변수요인들을 제어할 수 있다는 것을 보며 매력을 느꼈기 때문입니다.
        <br><br>
        그 이후로, 스스로 스마트팜에 관련된 기업이나 사업등을 알아보고 조사해보기도 하고, 동아리에서 스마트팜을 주제로 한 발표를 하기도
        했습니다. </p>
        시간이 지나며 고등학교 3학년. 즉 대입을 준비하는 시즌이 되었고 타이밍이 마치 누가 절 도와주는 것처럼 대학에 진학하는 해인 </p> 2021년에 전북대학교에서 "스마트팜"학과를 신설한다는 공고를 보고
        저 곳에 가서 더 공부하고싶다. 라고 생각한 것 같습니다. </h4><br><br>

        <hr/>
        <a href="{% url 'single_pages:landing' %}">첫 화면으로 가기<i class="fa-solid fa-house"></i></a>

{% endblock %}

hw09/single_pages/templates/single_pages/armylife.html
{% extends './layout.html' %}
{% load static %}

{% block content %}
    <h1>About my army life</h1>
    <img src="{% static 'single_pages/images/kta.jpeg' %}" class="army-image" alt="KTA 훈련을 받고 있는 예비 카투사 훈련병들의 모습">
    <hr>

    <h2>군 복무 개요</h2>
    <p>2022년 11월 21일에 군입대 후, KATUSA(주한 미 8군 한국국 지원단)로 1년 6개월 동안 평택 CAMP HUMPHREYS에서 602항공 지원대대 / 찰리 중대 / 행정병으로 복무했고 2024년 5월 20일 육군 병장으로 만기 제대했습니다.</p>

    <h2>군 생활 경험</h2>
    <p>8주 간의 훈련를 마치고 602항공지원대대로 처음 배치 받았을 때의 기억이 새록새록합니다. 모든 것이 서툴고 낯설었습니다. 영어에 대해 자신감도 없었던 때라 말하기도 두려웠습니다.</p>
    <p>하지만 저희 중대의 중대장과 일등상사의 행정 업무를 보조하고 통역업무 등을 수행하며 말하기 실력을 키웠고, 감각을 유지하기 위해 미군들에게 먼저 대화를 시도해보며 노력했습니다. 미군들과 대화를 하면 할수록 조금씩 자신감도 생기고 자연스러워지기 시작했던 것 같습니다.</p>
    <p>정신 없이 주어진 행정업무와 중대의 기수로서 활동하고 나니 18개월이란 시간이 금방 끝나가 후임들과 작별인사를 하고 있었습니다. 어떻게 보면 정말 짧았던 시간이었습니다.</p>
    <p>KATUSA로서 미군과 같이 복무했던 것은 정말 잊을 수 없는 경험이었고, 저에게 보는 시야를 넓게 만들어줬던 시간이었습니다. 이러한 경험들을 자양분 삼아 제가 배우고 있는 분야에서도 더욱 더 발전하고 성장하고 싶습니다.</p>

    <hr>

    <h2>군 생활 사진</h2>

        <img src="{% static 'single_pages/images/etsimage.jpg' %}" class="army-image" alt="전역식 당일 부대를 나가기 전 중대원들과">
        사진 1) 2024/5/20. 전역식 당일 부대를 나가기 전 중대원들과 <hr>


        <img src="{% static 'single_pages/images/katusacoc.jpg' %}" class="army-image" alt="나의 첫 중대장이었던 CPT timothy.Lee 의 이취임식">
        사진 2) 2023/12/15. 나의 첫 중대장이었던 CPT timothy.Lee 의 이취임식 (change of command)을 마치며


    <hr>
    <a href="{% url 'single_pages:landing' %}" class="home-link">첫 화면으로 가기<i class="fa-solid fa-house"></i></a>
{% endblock %}

hw09/single_pages/templates/single_pages/index.html
{% extends './layout.html' %}
{% load static %}

{% block content %}
<h1>이현규 공간의</h1>

<button onclick="whatTimeIsIt()">현재시간<i class="fa-solid fa-clock"></i>은?</button>
<script type="text/javascript" src="{% static 'single_pages/js/what_time_is_it.js' %}"></script>
<hr>

<img src="{% static 'single_pages/images/jbnu.jpeg' %}" alt="전북대학교 로고" class="university-logo">
<h3><a href="https://www.jbnu.ac.kr/kor/">Go to JBNU home page<i class="fa-solid fa-link"></i></a></h3>
<p>안녕하세요. 전북대학교 스마트팜학과 21학번 이현규입니다. 반갑습니다.</p>
<h3>-----위 파란색 칸 항목 중에 알아보고 싶으신 번호를 클릭하셔서 들어가시면 됩니다.-----</h3>

<hr>

<p>아래 링크는 저의 git hub 저장소입니다. 부족하지만 열심히 노력해보겠습니다.</p>
<h3><a href="https://github.com/JBNUSFLEEHK?tab=repositories">Go to GitHub page<i class="fa-solid fa-link"></i></a></h3>

<hr>

<img src="{% static 'single_pages/images/smartfarm_image.jpg' %}" alt="스마트팜 이미지" class="smartfarm-image">

<script type="text/javascript" src="{% static 'single_pages/js/what_time_is_it.js' %}"></script>
{% endblock %}

hw09/single_pages/templates/single_pages/layout.html
<!DOCTYPE HTML>
{% load static %}
<html>

  <head>
    <meta charset="utf-8">
    <title> 이현규의 홈페이지</title>
      <link rel="stylesheet" href="{% static 'single_pages/css/practice.css' %}">

    <link rel="stylesheet" href="{% static 'single_pages/css/practice.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/172221c77b.js" crossorigin="anonymous"></script>
  </head>
  <body>
    <header>
      <nav>
        <a href="{% url 'single_pages:landing' %}"><i class="fa-solid fa-house"></i></a>
        <a href="{% url 'single_pages:naverblog' %}">Naver Blog</a>
        <a href="{% url 'single_pages:blog' %}">Blog</a>
        <a href="{% url 'single_pages:about_me' %}">About<i class="fa-solid fa-user"></i></a>
        <a href="{% url 'single_pages:army_life' %}">Army life</a>
      </nav>
      <hr>
    </header>

    <main role="main">
    {% block content %}{% endblock %}
    </main>
  </body>
</html>