hw11/blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
        path('<int:pk>/', views.single_post_page),
        path('blog/', views.blog, name='blog'),
        path('', views.index, name='index'),
        path('naverblog/', views.naverblog, name='naverblog'),
        path('aboutme/', views.about_me, name='about_me'),
        path('armylife/', views.army_life, name='army_life'),


]



hw11/se09_prj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls import include, path
urlpatterns = [
    path('', include('blog.urls')),
    path('blog/', include('blog.urls')),
    path("admin/", admin.site.urls),
    path("", include("todo_app.urls"))
]

hw11/todo_app/urls.py
from django.urls import path
from todo_app import views

urlpatterns = [
    path("todo", views.ListListView.as_view(), name="index"),
    path("list/<int:list_id>/", views.ItemListView.as_view(), name="list"),
    # CRUD patterns for ToDoLists
    path("list/add/", views.ListCreate.as_view(), name="list-add"),
    path(
        "list/<int:pk>/delete/", views.ListDelete.as_view(), name="list-delete"
    ),
    # CRUD patterns for ToDoItems
    path(
        "list/<int:list_id>/item/add/",
        views.ItemCreate.as_view(),
        name="item-add",
    ),
    path(
        "list/<int:list_id>/item/<int:pk>/",
        views.ItemUpdate.as_view(),
        name="item-update",
    ),
    path(
        "list/<int:list_id>/item/<int:pk>/delete/",
        views.ItemDelete.as_view(),
        name="item-delete",
    ),
]

hw11/blog/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=30)
    content = models.TextField()

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'[{self.pk}]{self.title}'

    def get_absolute_url(self):
        return f'/blog/{self.pk}/'

hw11/todo_app/models.py
from django.utils import timezone

from django.db import models
from django.urls import reverse

def one_week_hence():
    return timezone.now() + timezone.timedelta(days=7)

class ToDoList(models.Model):
    title = models.CharField(max_length=100, unique=True)

    def get_absolute_url(self):
        return reverse("list", args=[self.id])

    def __str__(self):
        return self.title

class ToDoItem(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(null=True, blank=True)
    created_date = models.DateTimeField(auto_now_add=True)
    due_date = models.DateTimeField(default=one_week_hence)
    todo_list = models.ForeignKey(ToDoList, on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse(
            "item-update", args=[str(self.todo_list.id), str(self.id)]
        )

    def __str__(self):
        return f"{self.title}: due {self.due_date}"

    class Meta:
        ordering = ["due_date"]

hw11/blog/views.py
from django.shortcuts import render
from .models import Post

def blog(request):
    posts = Post.objects.all().order_by('-pk')
    return render(request,'blog/blog.html',{'title' : 'Blog', 'posts': posts})

def single_post_page(request, pk):
    post = Post.objects.get(pk=pk)

    return render(
        request,
        'blog/single_post_page.html',
        {
            'post': post
        }
    )
def index(request):
    return render(request,'blog/index.html', {'title':'Home'})

def about_me(request):
    return render(request,'blog/about_me.html', {'title': 'About Me'})


def naverblog(request):
    return render(request,'blog/naver_blog.html', {'title': 'Naver Blog'})

def army_life(request):
    return render(request, 'blog/armylife.html', {'title': 'Army life'})



hw11/single_pages/views.py
from django.shortcuts import render

# Create your views here.

hw11/todo_app/views.py
from django.urls import reverse, reverse_lazy

from django.views.generic import (
    ListView,
    CreateView,
    UpdateView,
    DeleteView,
)
from .models import ToDoItem, ToDoList

class ListListView(ListView):
    model = ToDoList
    template_name = "todo_app/index.html"

class ItemListView(ListView):
    model = ToDoItem
    template_name = "todo_app/todo_list.html"

    def get_queryset(self):
        return ToDoItem.objects.filter(todo_list_id=self.kwargs["list_id"])

    def get_context_data(self):
        context = super().get_context_data()
        context["todo_list"] = ToDoList.objects.get(id=self.kwargs["list_id"])
        return context

class ListCreate(CreateView):
    model = ToDoList
    fields = ["title"]

    def get_context_data(self):
        context = super(ListCreate, self).get_context_data()
        context["title"] = "Add a new list"
        return context

class ItemCreate(CreateView):
    model = ToDoItem
    fields = [
        "todo_list",
        "title",
        "description",
        "due_date",
    ]

    def get_initial(self):
        initial_data = super(ItemCreate, self).get_initial()
        todo_list = ToDoList.objects.get(id=self.kwargs["list_id"])
        initial_data["todo_list"] = todo_list
        return initial_data

    def get_context_data(self):
        context = super(ItemCreate, self).get_context_data()
        todo_list = ToDoList.objects.get(id=self.kwargs["list_id"])
        context["todo_list"] = todo_list
        context["title"] = "Create a new item"
        return context

    def get_success_url(self):
        return reverse("list", args=[self.object.todo_list_id])

class ItemUpdate(UpdateView):
    model = ToDoItem
    fields = [
        "todo_list",
        "title",
        "description",
        "due_date",
    ]

    def get_context_data(self):
        context = super(ItemUpdate, self).get_context_data()
        context["todo_list"] = self.object.todo_list
        context["title"] = "Edit item"
        return context

    def get_success_url(self):
        return reverse("list", args=[self.object.todo_list_id])
class ListDelete(DeleteView):
    model = ToDoList
    # You have to use reverse_lazy() instead of reverse(),
    # as the urls are not loaded when the file is imported.
    success_url = reverse_lazy("index")

class ItemDelete(DeleteView):
    model = ToDoItem

    def get_success_url(self):
        return reverse_lazy("list", args=[self.kwargs["list_id"]])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["todo_list"] = self.object.todo_list
        return context

hw11/blog/templates/blog/about_me.html
{% extends './layout.html' %}
{% load static%}
{% block content %}



  <h1>자기 소개</h1>
        <h3>안녕하십니까. 제 이름은 이현규입니다.</h3>
        <h3>2002년생(23살)이고 현재 전북대학교 스마트팜학과에 재학중입니다.</h3>

        <img src="{% static 'blog/images/profile.jpg'%}" width="300px">

        <hr/>

        <h3>(취미)</h3>
        <h4>: 저녁에 (혼자) 제가 좋아하는 노래를 들으며 러닝하는 것을 좋아합니다.
            또는 친구들과 함께 축구 or 풋살도 좋습니다. </h4></p>
        <h3>(MBTI)</h3> </p>

        <h4>: ENFP 입니다. E와 I의 비율의 거의 비슷하지만 "E"가  55%이니 ENFP로 하지요. ^_^ </h4></p>
        <h3>(좋아하는 음식)</h3> </p>

        <h4>: 저는 특히 서구권 음식을 좋아하는 것 같습니다. (스파게티, 피자, 햄버거를 특히 !@ 좋아합니다.)
        </p>BUT 언제나 맛있는 한식도 환영입니다.(누구나 아는 김치찌개, 갈비찜, 제육볶음, etc..)</h4>
        <hr/>
        <h3>(거주지) </h3></p>
        <h4>: 제 본가는 서울 금천구에 위치하고 있습니다. </h4></p>

        <h3>(가족 관계)</h3> </p>
        <h4>: 아버지, 어머니 그리고 제 위에 형 2명이 있습니다. (총 5명)</h4> </p>
        <h3>(스마트팜학과에 진학한 이유)</h3> </p> <h4> : 고등학교 시절, 스마트팜이라는 농업 분야를 처음 접했고 흥미가 생기기
    
        시작했습니다. </p>
        대부분이 생각하는 농업은 힘들고, 지구 대기 날씨의 영향이 절대적이고 그 해 농사의 결과를 결정하는 것이었습니다. </p>
        하지만 스마트팜 기술의 발전을 통해 이러한 문제점들과 변수요인들을 제어할 수 있다는 것을 보며 매력을 느꼈기 때문입니다.
        <br><br>
        그 이후로, 스스로 스마트팜에 관련된 기업이나 사업등을 알아보고 조사해보기도 하고, 동아리에서 스마트팜을 주제로 한 발표를 하기도
        했습니다. </p>
        시간이 지나며 고등학교 3학년. 즉 대입을 준비하는 시즌이 되었고 타이밍이 마치 누가 절 도와주는 것처럼 대학에 진학하는 해인 </p> 2021년에 전북대학교에서 "스마트팜"학과를 신설한다는 공고를 보고
        저 곳에 가서 더 공부하고싶다. 라고 생각한 것 같습니다. </h4><br><br>

        <hr/>
        <a href="{% url 'blog:index' %}">첫 화면으로 가기<i class="fa-solid fa-house"></i></a>

{% endblock %}

hw11/blog/templates/blog/armylife.html
{% extends './layout.html' %}
{% load static %}

{% block content %}
    <h1>About my army life</h1>
    <img src="{% static 'blog/images/kta.jpg' %}">
    <hr>

    <h2>군 복무 개요</h2>
    <p>2022년 11월 21일에 군입대 후, KATUSA(주한 미 8군 한국국 지원단)로 1년 6개월 동안 평택 CAMP HUMPHREYS에서 602항공 지원대대 / 찰리 중대 / 행정병으로 복무했고 2024년 5월 20일 육군 병장으로 만기 제대했습니다.</p>

    <h2>군 생활 경험</h2>
    <p>8주 간의 훈련를 마치고 602항공지원대대로 처음 배치 받았을 때의 기억이 새록새록합니다. 모든 것이 서툴고 낯설었습니다. 영어에 대해 자신감도 없었던 때라 말하기도 두려웠습니다.</p>
    <p>하지만 저희 중대의 중대장과 일등상사의 행정 업무를 보조하고 통역업무 등을 수행하며 말하기 실력을 키웠고, 감각을 유지하기 위해 미군들에게 먼저 대화를 시도해보며 노력했습니다. 미군들과 대화를 하면 할수록 조금씩 자신감도 생기고 자연스러워지기 시작했던 것 같습니다.</p>
    <p>정신 없이 주어진 행정업무와 중대의 기수로서 활동하고 나니 18개월이란 시간이 금방 끝나가 후임들과 작별인사를 하고 있었습니다. 어떻게 보면 정말 짧았던 시간이었습니다.</p>
    <p>KATUSA로서 미군과 같이 복무했던 것은 정말 잊을 수 없는 경험이었고, 저에게 보는 시야를 넓게 만들어줬던 시간이었습니다. 이러한 경험들을 자양분 삼아 제가 배우고 있는 분야에서도 더욱 더 발전하고 성장하고 싶습니다.</p>

    <hr>

    <h2>군 생활 사진</h2>

        <img src="{% static 'blog/images/etsimage.jpg' %}" width="300px">
        사진 1) 2024/5/20. 전역식 당일 부대를 나가기 전 중대원들과 <hr>

        <img src="{% static 'blog/images/katusacoc.jpg' %}" width="300px">
        사진 2) 2023/12/15. 나의 첫 중대장이었던 CPT timothy.Lee 의 이취임식 (change of command)을 마치며

    <hr>
    <a href="{% url 'blog:index' %}">첫 화면으로 가기<i class="fa-solid fa-house"></i></a>
{% endblock %}

hw11/blog/templates/blog/blog.html
{% extends './layout.html' %}

{% block content %}
<h1>ACTIVITY</h1>

{% for p in posts %}
    <hr/>
    <h2>{{ p.title }}</h2>
    <h4>{{ p.created_at }}</h4>
    <p>{{ p.content }}</p>
{% endfor %}
{% endblock %}

hw11/blog/templates/blog/index.html
{% extends './layout.html' %}
{% load static %}

{% block content %}
<h1>이현규 공간의</h1>

<button onclick="whatTimeIsIt()">현재시간<i class="fa-solid fa-clock"></i>은?</button>
<script type="text/javascript" src="{% static 'blog/js/what_time_is_it.js' %}"></script>
<hr>

<img src="{% static 'blog/images/jbnu.jpg' %}" width="300px">
<h3><a href="https://www.jbnu.ac.kr/kor/">Go to JBNU home page<i class="fa-solid fa-link"></i></a></h3>
<p>안녕하세요. 전북대학교 스마트팜학과 21학번 이현규입니다. 반갑습니다.</p>
<h3>-----위 파란색 칸 항목 중에 알아보고 싶으신 번호를 클릭하셔서 들어가시면 됩니다.-----</h3>

<hr>

<p>아래 링크는 저의 git hub 저장소입니다. 부족하지만 열심히 노력해보겠습니다.</p>
<h3><a href="https://github.com/JBNUSFLEEHK?tab=repositories">Go to GitHub page<i class="fa-solid fa-link"></i></a></h3>

<hr>

<img src="{% static 'blog/images/smartfarm_image.jpg' %}" width="300px">

<script type="text/javascript" src="{% static 'blog/js/what_time_is_it.js' %}"></script>
{% endblock %}

hw11/blog/templates/blog/layout.html
{% load static %}
<!DOCTYPE HTML>

<html>

  <head>
    <meta charset="utf-8">
    <title> 이현규의 홈페이지</title>
    <link rel="stylesheet" href="{% static 'blog/css/practice.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/172221c77b.js" crossorigin="anonymous"></script>
  </head>
  <body>
    <header>
      <nav>
          
        <a href="{% url 'blog:index' %}"><i class="fa-solid fa-house"></i></a>
        <a href="{% url 'blog:naverblog' %}">Naver Blog</a>
        <a href="{% url 'blog:about_me' %}">About<i class="fa-solid fa-user"></i></a>
        <a href="{% url 'blog:army_life' %}">Army life</a>
        <a href="{% url 'blog:blog' %}">Blog</a>
      </nav>
      <hr>
    </header>

    <main role="main">
    {% block content %}{% endblock %}
    </main>
  </body>
</html>

hw11/blog/templates/blog/naver_blog.html
{% extends './layout.html' %}

{% block content %}
<h1>나의 Blog</h1>

<hr>

<h2>이런!!!ㅠㅠ</h2>

<p>네이버 블로그 계정은 존재하지만 현재 활동하고 있지 않습니다.</p>
<p>나중에 기회가 된다면 블로그도 해보도록 하겠습니다.
추억으로 남길 수 있으니까요~</p>

<hr>

<h3><a href="https://blog.naver.com/hkyulee2002">네이버 블로그 방문하기<i class="fa-solid fa-link"></i></a></h3>

<hr>

<a href="{% url 'blog:index' %}" class="home-link">첫 화면으로 가기<i class="fa-solid fa-house"></i></a>

{% endblock %}

hw11/blog/templates/blog/single_post_page.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>{{ post.title }} - Blog</title>
</head>
<body>
<nav>
    <a href="/blog/">Blog</a>
</nav>
<h1>{{ post.title }}</h1>
<h4>{{ post.created_at }}</h4>
<p>{{ post.content }}</p>
<hr/>
</body>
</html>

hw11/todo_app/templates/todo_app/index.html
<!-- todo_list/todo_app/templates/todo_app/index.html -->

{% extends "base.html" %}
{% block content %}
<!--index.html-->
{% if object_list %}
<h3>All my lists</h3>
{% endif %}
<ul>
    {% for todolist in object_list %}
    <li>
        <div
            role="button"
            onclick="location.href='{% url "list" todolist.id %}'">
            {{ todolist.title }}
        </div>
    </li>
    {% empty %}
    <h4>You have no lists!</h4>
    {% endfor %}
</ul>
<p>
    <input
        value="Add a new list"
        type="button"
        onclick="location.href='{% url "list-add" %}'"/>
</p>
{% endblock %}

hw11/todo_app/templates/todo_app/todo_list.html
{% extends "base.html" %}

{% block content %}
<div>
    <div>
        <div>
            <h3>Edit list:</h3>
            <h5>{{ todo_list.title | upper }}</h5>
        </div>
        <ul>
            {% for todo in object_list %}
            <li>
                <div>
                    <div
                        role="button"
                        onclick="location.href=
                        '{% url "item-update" todo_list.id todo.id %}'">
                        {{ todo.title }}
                        (Due {{ todo.due_date | date:"l, F j" }})
                    </div>
                </div>
            </li>
            {% empty %}
            <p>There are no to-do items in this list.</p>
            {% endfor %}
        </ul>
        <p>
            <input
                value="Add a new item"
                type="button"
                onclick="location.href=
                '{% url "item-add" todo_list.id %}'" />
            <input
                value="Delete this list"
                type="button"
                onclick="location.href=
                '{% url "list-delete" todo_list.id %}'" />
        </p>
    </div>
</div>
{% endblock %}

hw11/todo_app/templates/todo_app/todoitem_confirm_delete.html
{% extends "base.html" %}

{% block content %}

<h3>Delete To-do Item</h3>

<p>Are you sure you want to delete the item: <b>{{ object.title }}</b>
   from the list <i>{{ todo_list.title }}</i>?</p>

<form method="POST">
    {% csrf_token %}
    <input
        value="Yes, delete."
        type="submit">
    <input
        value="Cancel"
        type="button"
        onclick="location.href='{% url "list" todo_list.id %}';">
</form>

{% endblock %}

hw11/todo_app/templates/todo_app/todoitem_form.html
{% extends "base.html" %}

{% block content %}

<h3>{{ title }}</h3>
<form method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input
        value="Submit"
        type="submit">
    <input
        value="Cancel"
        type="button"
        onclick="location.href='{% url "list" todo_list.id %}'">
    {% if object %}
        <input
            value="Delete this item"
            type="button"
            onclick="location.href=
            '{% url "item-delete" todo_list.id object.id %}'">
    {% endif %}
</form>

{% endblock %}

hw11/todo_app/templates/todo_app/todolist_confirm_delete.html
{% extends "base.html" %}

{% block content %}
<!--todolist_confirm_delete.html-->

<h3>Delete List</h3>

<p>Are you sure you want to delete the list <i>{{ object.title }}</i>?</p>

<form method="POST">
    {% csrf_token %}
    <input
        value="Yes, delete."
        type="submit">
</form>
<input
    value="Cancel"
    type="button"
    onclick="location.href='{% url "index" %}';">

{% endblock %}

hw11/todo_app/templates/todo_app/todolist_form.html
{% extends "base.html" %}

{% block content %}

<h3>{{ title }}</h3>
<div>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input
                value="Save"
                type="submit">
            <input
                value="Cancel"
                type="button"
                onclick="location.href='{% url "index" %}';">
        </form>
    </div>
</div>

{% endblock %}